image: docker:latest

services:
  - docker:dind

stages:
  - Build Image
  - Test Dev Image

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/morph1904/tyger2:dev

docker build:
  stage: Build Image
  script:  
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY/morph1904/tyger2:dev -t morph1904/tyger2:dev .
  - docker push $CI_REGISTRY/morph1904/tyger2:dev
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
  #- docker build -t morph1904/tyger2:dev .
  - docker push morph1904/tyger2:dev

test:
  stage: Test Dev Image
  before_script:
    - docker info
    - BRANCH_LOWER=$(echo "$CI_COMMIT_REF_NAME" | awk '{print tolower($0)}')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run -d -p 80:80 -p 443:443 -p 9090:9090 --name tyger2test $CONTAINER_TEST_IMAGE

  script:
    - docker exec tyger2test /bin/bash /test/check-response.sh