image: docker:stable

stages:
  - Build image

docker build:
  stage: Build image
  script:  
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY/morph1904/tyger2:dev .
  - docker push $CI_REGISTRY/morph1904/tyger2:dev